# zsh options
setopt HIST_IGNORE_SPACE
setopt IGNORE_EOF

# set up 
eval "$(/bin/bash -c 'fasd --init auto' 2>/dev/null)"

# zsh git prompt is nice :)
git clone https://github.com/olivierverdier/zsh-git-prompt.git ~/.zsh-git-prompt > /dev/null 2>&1
source ~/.zsh-git-prompt/zshrc.sh > /dev/null 2>&1

# zsh prompt
PROMPT='%? | %d $(git_super_status)
%# '

fpath=(~/.zsh $fpath)

# common shell profile
source ~/.profile
